# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 694f3581d0117af56cc9ebf67135921f1429b544b3b271d107fa6945fbb8fd46ab2cad465ce2bd50dfad2c5e4eebe259b34de3481d5fc72b58704f310a7e7ba5

test:
  secret_key_base: 7e33bbfeddb30fefd23c062cb40ac33809cdf7edab5a620f3279c23276866a5d0da4bbbbafda89273b486993d3a8eea960f48cfbecabba048cb6a8e6e7f41b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
